// EVENTS
GET http://localhost:3000/events

###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "New Event",
  "description": "This is a new event",
  "date": "2024-01-01T00:00:00",
  "price": 100 
}

###
@eventId = {{ createEvent.response.body.id }}

###
GET http://localhost:3000/events/{{ eventId }}

###
PATCH http://localhost:3000/events/{{ eventId }}
Content-Type: application/json

{
  "name": "New Event Updated",
  "description": "This is a new event updated",
  "date": "2024-01-01T00:00:00",
  "price": 100 
}

###
DELETE http://localhost:3000/events/{{ eventId }}

// SPOTS
###
GET http://localhost:3000/events/{{eventId}}/spots

###
# @name createSpot
POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
  "name": "A1"
}

// RESERVES
###
@spotName = {{ createSpot.response.body.name }}

###
POST http://localhost:3000/events/{{eventId}}/reserve
Content-Type: application/json

{
  "spots": ["{{ spotName }}"],
  "ticket_kind": "full",
  "email": "teste@teste.com"
}